### ISSUE TITLE
Issue with importing from wrong place

### ISSUE THREAD

**Issue by stevewarsa** [Sammons/ts-import-assistance#15]
If I type Http and highlight and invoke (keybinding ctrl+i), it imports:

import {Http} from '@angular/http/src/http';

But should be:

import {Http} from '@angular/http';

**Comment by Sammons** [comment]
I'll take a look - thanks for reporting in. If you can, please link to some code I can use to reproduce.

**Comment by stevewarsa** [comment]
well, I don't have any code, but here is how you can reproduce it:

using node 6.6.0

install angular-cli

My current version as I run this is 1.0.0-beta.14.

Then create a new project:

ng new myproject

cd myproject/src/app/shared

ng g s system --flat

open system.service.ts (myproject/src/app/shared) in VS Code

in the constructor, in between the parens, type 

http:Http

Http will have a red line under it

Highlight Http and invoke your plugin to generate the import statement

You should see the problem then.

Thanks,
Steve

**Comment by Sammons** [comment]
I should also mention, I still use this plugin for my own convenience but others are gaining popularity over this one. This one just uses text manipulation and heuristics to get the job done, where others are more formally correct, there's a (closed) thread where some are discussed here - https://github.com/Microsoft/TypeScript/issues/188#issuecomment-241484681.

I just know that when I wrote this originally there weren't really other solutions, so I thought I'd share that.

I'll fix this as soon as I'm able to, but it will still be a few days because of regular work keeping me busy.

**Comment by Sammons** [comment]
@stevewarsa following your steps when I ran the plugin and got

```
import {Http} from '@angular/http/src/http';
```

what import did it find for you?

**Comment by Sammons** [comment]
@stevewarsa realizing what I said is exactly what you said the problem was (facepalm).

I know what the problem is.

**Comment by Sammons** [comment]
@stevewarsa I am stopping development on this project in leu of https://marketplace.visualstudio.com/items?itemName=rbbit.typescript-hero which has much more focused development behind it. I will continue to monitor this repo for new issues, but it doesn't make good sense to keep building when there is a technically superior solution available.
